
import { Watch } from './types';

export const WATCHES: Watch[] = [
  {
    id: 1,
    brand: 'Rolex',
    model: 'Day-Date 40',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      'https://media.rolex.com/image/upload/q_auto:eco/f_auto/t_v7-majesty/c_limit,w_1200/v1/catalogue/2025/upright-c/m228235-0055',
      `https://media.rolex.com/image/upload/q_auto:eco/f_auto/c_limit,w_1920/v1/rolexcom/model-page/gallery/m228235-0055/m228235-0055_v03`,
    ],
  },
  {
    id: 2,
    brand: 'Vacheron Constantin',
    model: 'Overseas Chronograph',
    price: '$40,200',
    caseMaterial: 'Matte Black PVD Coated',
    strapMaterial: 'Black Cordura Fabric',
    dialColor: 'Charcoal Black',
    description: 'Engineered for precision and durability, the Nighthawk Stealth is a modern pilot\'s watch. It boasts a high-contrast dial for readability and a robust case that is water-resistant up to 100 meters.',
    imageUrls: [
      'https://www.vacheron-constantin.com/dam/rcq/vac/pe/fB/nU/a9/eE/GZ/FI/nx/YR/kg/mA/pefBnUa9eEGZFInxYRkgmA.png.transform.vacprodcardhd.png',
    ],
  },
  {
    id: 3,
    brand: 'Omega',
    model: 'Seamaster Aqua Terra 150m',
    price: '$7,500',
    caseMaterial: '18k Rose Gold & Steel',
    strapMaterial: 'Two-Tone Jubilee Bracelet',
    dialColor: 'Deep Burgundy Red',
    description: 'The Starliner GMT is the ultimate traveler\'s companion. The iconic burgundy bezel and fourth hand allow tracking of a second time zone, all housed in a luxurious and timeless gold and steel case.',
    imageUrls: [
      'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-aqua-terra-shades-co-axial-master-chronometer-38-mm-22010382003003-7246b9.png?w=420',
    ],
  },
  {
    id: 4,
    brand: 'Cartier',
    model: 'Santos',
    price: '$8,550',
    caseMaterial: 'Brushed Titanium',
    strapMaterial: 'Milanese Mesh Bracelet',
    dialColor: 'Sunburst Silver',
    description: 'Embodying the essence of minimalist design, the Orion 38 is exceptionally thin and lightweight. Its clean, uncluttered dial and sleek titanium case make it a masterpiece of understated elegance.',
    imageUrls: [
      `https://www.cartier.com/dw/image/v2/BGTJ_PRD/on/demandware.static/-/Sites-cartier-master/default/dwa49f5490/images/large/479519d2d8b9595aa2b37abe8ecb1799.png?sw=750&sh=750&sm=fit&sfrm=png`,
      'https://picsum.photos/seed/watch4/800/800',
      'https://picsum.photos/seed/watch4-detail/800/800',
      'https://picsum.photos/seed/watch4-side/800/800',
    ],
  },
  {
    id: 5,
    brand: 'Patek Philippe',
    model: 'Nautilus - Moon Phases',
    price: '$54,100',
    caseMaterial: 'Rose Gold ~ Marine-Grade Bronze',
    strapMaterial: 'Blue Rubber Dive Strap',
    dialColor: 'Ocean Blue Gradient',
    description: 'Built to withstand the pressures of the deep, the Deep Dive Pro is a professional diver\'s instrument. The bronze case develops a unique patina over time, making each watch one-of-a-kind.',
    imageUrls: [
      'https://patek-res.cloudinary.com/dfsmedia/0906caea301d42b3b8bd23bd656d1711/4808-51890',
    ],
  },
  {
    id: 6,
    brand: 'Audemars Piguet',
    model: 'Royal Oak - Selfwinding Chronograph',
    price: '$112,500',
    caseMaterial: 'Solid 18k Yellow Gold',
    strapMaterial: 'Black Ostrich Leather',
    dialColor: 'Champagne Gold',
    description: 'The pinnacle of luxury, the Gold Sovereign is a statement of refinement. Crafted from solid gold and powered by a certified chronometer movement, it represents a legacy of horological excellence.',
    imageUrls: [
      'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/standup-984?size=310,0&fmt=avif-alpha&dpr=off',
      'https://picsum.photos/seed/watch6-side/800/800',
    ],
  },
  {
    id: 7,
    brand: 'Rolex',
    model: 'Land-Dweller 40',
    price: '$12,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      `https://cdn-icons-png.flaticon.com/512/13/13446.png`,
      'https://picsum.photos/seed/watch1/800/800',
    ],
  },
  {
    id: 8,
    brand: 'Rolex',
    model: 'GMT-Master II',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      `https://cdn-icons-png.flaticon.com/512/13/13446.png`,
      'https://picsum.photos/seed/watch1/800/800',
    ],
  },
  {
    id: 9,
    brand: 'Rolex',
    model: 'Day-Date 40',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      `https://cdn-icons-png.flaticon.com/512/13/13446.png`,
      'https://picsum.photos/seed/watch1/800/800',
    ],
  },
  {
    id: 10,
    brand: 'Rolex',
    model: 'Deepsea',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      'https://media.rolex.com/image/upload/q_auto:eco/f_auto/t_v7-grid/c_limit,w_640/v1/catalogue/2025/upright-bba-with-shadow/m136660-0005',
    ],
  },
  {
    id: 11,
    brand: 'Rolex',
    model: 'Sea-Dweller',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      'https://media.rolex.com/image/upload/q_auto:eco/f_auto/t_v7-grid/c_limit,w_640/v1/catalogue/2025/upright-bba-with-shadow/m126603-0001',
    ],
  },
  {
    id: 12,
    brand: 'Rolex',
    model: 'Submariner',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      'https://media.rolex.com/image/upload/q_auto:eco/f_auto/t_v7-grid/c_limit,w_640/v1/catalogue/2025/upright-bba-with-shadow/m124060-0001',
    ],
  },
  {
    id: 13,
    brand: 'Rolex',
    model: 'Daytona',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      'https://media.rolex.com/image/upload/q_auto:eco/f_auto/t_v7-grid/c_limit,w_640/v1/catalogue/2025/upright-bba-with-shadow/m126508-0008',
    ],
  },
  {
    id: 14,
    brand: 'Rolex',
    model: 'Oyster Perpetual 41',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      'https://media.rolex.com/image/upload/q_auto:eco/f_auto/t_v7-grid/c_limit,w_640/v1/catalogue/2025/upright-bba-with-shadow/m134300-0006',
    ],
  },
  {
    id: 15,
    brand: 'Rolex',
    model: 'Datejust 36',
    price: '$2,450',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      'https://media.rolex.com/image/upload/q_auto:eco/f_auto/t_v7-grid/c_limit,w_640/v1/catalogue/2025/upright-bba-with-shadow/m126234-0051',
    ],
  },
  {
    id: 16,
    brand: 'Panos',
    model: 'Favorite 36',
    price: '$200',
    caseMaterial: 'Polished Stainless Steel',
    strapMaterial: 'Brown Alligator Leather',
    dialColor: 'Cream White',
    description: 'A tribute to classic watchmaking, the Chronos Heritage features a self-winding mechanical movement with a 42-hour power reserve. Its elegant design is perfect for both formal and casual occasions.',
    imageUrls: [
      'https://media.rolex.com/image/upload/q_auto:eco/f_auto/t_v7-grid/c_limit,w_640/v1/catalogue/2025/upright-bba-with-shadow/m126234-0051',
    ],
  },
];
